import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, Fonts, MaxContentWidth, SHADOWS, Spacing } from '@/constants/theme';

export const armorShopStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  scrollContent: { flexGrow: 1, paddingBottom: Spacing.six },
  content: { width: '100%', maxWidth: MaxContentWidth, alignSelf: 'center', padding: Spacing.three, gap: Spacing.three },
  profileBar: { backgroundColor: COLORS.cardBackground, borderRadius: BORDER_RADIUS.card, padding: Spacing.four, gap: Spacing.two, ...SHADOWS.soft },
  title: { color: COLORS.textPrimary, fontFamily: Fonts.display, fontSize: 24 },
  talentBadge: { alignSelf: 'flex-start', backgroundColor: COLORS.primarySoft, borderRadius: BORDER_RADIUS.badge, paddingHorizontal: Spacing.three, paddingVertical: 10 },
  talentText: { color: COLORS.primary, fontFamily: Fonts.display, fontSize: 17 },
  heroCard: { alignItems: 'center', backgroundColor: COLORS.accentSoft, borderRadius: BORDER_RADIUS.card, padding: Spacing.four, gap: Spacing.two },
  heroCardAura: { backgroundColor: '#FFF8D9', borderWidth: 2, borderColor: COLORS.secondary },
  heroLabel: { color: COLORS.textSecondary, fontFamily: Fonts.display, fontSize: 15 },
  character: { fontFamily: Fonts.sans, fontSize: 74 },
  equippedRow: { minHeight: 34, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: Spacing.two },
  equippedChip: { backgroundColor: COLORS.cardBackground, borderRadius: BORDER_RADIUS.badge, paddingHorizontal: 12, paddingVertical: 6 },
  equippedText: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 14, fontWeight: '700' },
  emptyText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 14 },
  sectionTitle: { color: COLORS.textPrimary, fontFamily: Fonts.display, fontSize: 21, marginTop: Spacing.two },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.three },
  itemCard: { width: '47%', flexGrow: 1, minWidth: 145, borderWidth: 2, borderColor: 'transparent', borderRadius: BORDER_RADIUS.card, padding: Spacing.three, gap: Spacing.two, ...SHADOWS.soft },
  itemCardMaxTier: { borderColor: COLORS.secondary, backgroundColor: '#FFF8D9' },
  itemEmoji: { fontFamily: Fonts.sans, fontSize: 42 },
  bonusBadge: { alignSelf: 'flex-start', backgroundColor: COLORS.secondary, borderRadius: BORDER_RADIUS.badge, paddingHorizontal: 10, paddingVertical: 4 },
  seasonalBadge: { backgroundColor: COLORS.mint },
  bonusText: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 12, fontWeight: '800' },
  itemName: { color: COLORS.textPrimary, fontFamily: Fonts.display, fontSize: 17 },
  itemDescription: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, minHeight: 38 },
  tierBadge: { alignSelf: 'flex-start', backgroundColor: COLORS.cardBackground, borderRadius: BORDER_RADIUS.badge, paddingHorizontal: 10, paddingVertical: 4 },
  tierBadgeText: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 12, fontWeight: '800' },
  actionRow: { flexDirection: 'row', gap: 8 },
  actionButton: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.primary, borderRadius: BORDER_RADIUS.button, paddingHorizontal: Spacing.two },
  equipButton: { backgroundColor: COLORS.accent },
  equippedButton: { backgroundColor: COLORS.success },
  upgradeButton: { backgroundColor: COLORS.secondary },
  buttonText: { fontFamily: Fonts.sans, color: COLORS.textOnPrimary, fontSize: 15, fontWeight: '800', textAlign: 'center' },
  buttonTextSmall: { fontFamily: Fonts.sans, fontSize: 13 },
  pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
  modalBackdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(41, 42, 45, 0.38)', padding: Spacing.four },
  modalCard: { width: '100%', maxWidth: 360, alignItems: 'center', backgroundColor: COLORS.surfaceOpaque, borderRadius: BORDER_RADIUS.card, padding: Spacing.five, gap: Spacing.three, ...SHADOWS.soft },
  modalEmoji: { fontFamily: Fonts.sans, fontSize: 72 },
  modalTitle: { color: COLORS.textPrimary, fontFamily: Fonts.display, fontSize: 22, textAlign: 'center' },
  modalButton: { width: '100%', minHeight: 52, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.primary, borderRadius: BORDER_RADIUS.button },
});
