import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, Fonts, SHADOWS } from '@/constants/theme';

export const gratitudeStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  keyboardView: { flex: 1 },
  scrollContent: { alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48 },
  content: { width: '100%', maxWidth: 520 },
  backButton: { alignSelf: 'flex-start', paddingHorizontal: 14, paddingVertical: 10, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.surfaceMuted },
  backText: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 14, fontWeight: '800' },
  header: { marginTop: 22, marginBottom: 18 },
  title: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 27, lineHeight: 36 },
  date: { fontFamily: Fonts.sans, marginTop: 5, color: COLORS.textSecondary, fontSize: 14, fontWeight: '700' },
  card: { ...SHADOWS.soft, marginBottom: 16, padding: 20, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  tabRow: { flexDirection: 'row', gap: 8, marginBottom: 18, padding: 5, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.surfaceMuted },
  tabButton: { flex: 1, alignItems: 'center', paddingVertical: 11, borderRadius: BORDER_RADIUS.badge },
  tabButtonActive: { ...SHADOWS.soft, backgroundColor: COLORS.cardBackground },
  tabText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 14, fontWeight: '800' },
  tabTextActive: { color: COLORS.primary },
  categoryRow: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  categoryChip: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.surfaceMuted },
  categoryChipActive: { backgroundColor: COLORS.primarySoft },
  categoryChipText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 13, fontWeight: '800' },
  categoryChipTextActive: { color: COLORS.primary },
  videoCard: { ...SHADOWS.soft, flexDirection: 'row', alignItems: 'center', marginBottom: 12, padding: 14, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  videoThumb: { width: 64, height: 64, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.card },
  videoThumbEmoji: { fontFamily: Fonts.sans, fontSize: 30 },
  videoBody: { flex: 1, marginLeft: 13 },
  videoCategoryBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 3, borderRadius: BORDER_RADIUS.badge, backgroundColor: '#FFF8E4', marginBottom: 6 },
  videoCategoryText: { fontFamily: Fonts.sans, color: COLORS.warning, fontSize: 10, fontWeight: '900' },
  videoTitle: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 15 },
  videoDuration: { fontFamily: Fonts.sans, marginTop: 4, color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  videoPlayButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primary, marginLeft: 8 },
  videoPlayIcon: { fontFamily: Fonts.sans, color: COLORS.textOnPrimary, fontSize: 16 },
  sectionTitle: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 19 },
  sectionGuide: { fontFamily: Fonts.sans, marginTop: 6, color: COLORS.textSecondary, fontSize: 13, lineHeight: 20, fontWeight: '600' },
  photoPreview: { height: 210, alignItems: 'center', justifyContent: 'center', marginTop: 16, overflow: 'hidden', borderRadius: 20, backgroundColor: COLORS.primarySoft },
  photoEmoji: { fontFamily: Fonts.sans, fontSize: 82 },
  photoCaption: { fontFamily: Fonts.sans, marginTop: 8, color: COLORS.textSecondary, fontSize: 13, fontWeight: '800' },
  photoButtons: { flexDirection: 'row', gap: 10, marginTop: 14 },
  photoButton: { flex: 1, minHeight: 52, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.accentSoft },
  photoButtonAlt: { backgroundColor: '#FFF8E4' },
  photoButtonText: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 15, fontWeight: '900' },
  input: { fontFamily: Fonts.sans, minHeight: 54, marginTop: 14, paddingHorizontal: 16, borderWidth: 2, borderColor: COLORS.disabled, borderRadius: 18, backgroundColor: COLORS.surfaceMuted, color: COLORS.textPrimary, fontSize: 15, fontWeight: '700' },
  safeHint: { fontFamily: Fonts.sans, marginTop: 8, color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  saveButton: { minHeight: 58, alignItems: 'center', justifyContent: 'center', marginTop: 16, paddingHorizontal: 12, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
  saveDisabled: { backgroundColor: COLORS.disabled },
  saveText: { fontFamily: Fonts.sans, color: COLORS.textOnPrimary, fontSize: 16, fontWeight: '900', textAlign: 'center' },
  feedHeader: { marginTop: 12, marginBottom: 14 },
  feedCard: { ...SHADOWS.soft, marginBottom: 18, overflow: 'hidden', borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  feedPhoto: { height: 175, alignItems: 'center', justifyContent: 'center' },
  feedEmoji: { fontFamily: Fonts.sans, fontSize: 70 },
  feedBody: { padding: 17 },
  friendRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  avatar: { fontFamily: Fonts.sans, fontSize: 24 },
  friendName: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 15, fontWeight: '900' },
  postTitle: { fontFamily: Fonts.sans, marginTop: 10, color: COLORS.textPrimary, fontSize: 16, lineHeight: 24, fontWeight: '700' },
  reactionRow: { flexDirection: 'row', gap: 6, marginTop: 14 },
  reactionButton: { flex: 1, minHeight: 44, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4, borderRadius: 14, backgroundColor: COLORS.surfaceMuted },
  reactionSelected: { backgroundColor: COLORS.primarySoft },
  reactionText: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 11, fontWeight: '800', textAlign: 'center' },
  pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] },
  modalBackdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: 'rgba(41,42,45,0.38)' },
  modalCard: { width: '100%', maxWidth: 390, alignItems: 'center', padding: 26, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.surfaceOpaque },
  modalEmoji: { fontFamily: Fonts.sans, fontSize: 48 },
  modalTitle: { fontFamily: Fonts.display, marginTop: 12, color: COLORS.textPrimary, fontSize: 21, textAlign: 'center' },
  modalBody: { fontFamily: Fonts.sans, marginTop: 10, color: COLORS.textSecondary, fontSize: 15, lineHeight: 23, fontWeight: '600', textAlign: 'center' },
  modalButton: { minHeight: 52, alignItems: 'center', justifyContent: 'center', alignSelf: 'stretch', marginTop: 20, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
});
