import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, SHADOWS } from '@/constants/theme';

export const homeStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  scrollContent: { flexGrow: 1, alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48 },
  content: { width: '100%', maxWidth: 520 },
  profileBar: { ...SHADOWS.soft, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 14, padding: 18, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  profileIdentity: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  profileAvatar: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primarySoft },
  profileInitial: { color: COLORS.primary, fontSize: 22, fontWeight: '900' },
  greeting: { color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  studentName: { color: COLORS.textPrimary, fontSize: 21, fontWeight: '900', marginTop: 2 },
  statsRow: { flexDirection: 'row', gap: 7 },
  statBadge: { paddingHorizontal: 11, paddingVertical: 9, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.surfaceMuted },
  statBadgePressed: { opacity: 0.72, transform: [{ scale: 0.96 }] },
  statText: { color: COLORS.textPrimary, fontSize: 13, fontWeight: '800' },
  avatarCard: { ...SHADOWS.soft, minHeight: 390, alignItems: 'center', marginTop: 18, padding: 20, overflow: 'hidden', borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.accentSoft },
  avatarHeading: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  eyebrow: { color: COLORS.accent, fontSize: 12, fontWeight: '900' },
  avatarTitle: { color: COLORS.textPrimary, fontSize: 21, fontWeight: '900', marginTop: 3 },
  levelBadge: { paddingHorizontal: 11, paddingVertical: 7, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.cardBackground },
  levelText: { color: COLORS.primary, fontSize: 11, fontWeight: '900' },
  speechBubble: { zIndex: 2, alignSelf: 'flex-end', maxWidth: 238, marginTop: 10, marginRight: 8, paddingHorizontal: 16, paddingVertical: 12, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  speechText: { color: COLORS.textPrimary, fontSize: 14, lineHeight: 20, fontWeight: '800' },
  speechTail: { position: 'absolute', right: 28, bottom: -8, width: 16, height: 16, transform: [{ rotate: '45deg' }], backgroundColor: COLORS.cardBackground },
  avatarButton: { flex: 1, width: '100%', alignItems: 'center', justifyContent: 'center', minHeight: 210 },
  avatarPressed: { transform: [{ scale: 0.96 }] },
  aura: { width: 195, height: 195, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: '#FFF8D9' },
  helmet: { fontSize: 30, lineHeight: 35 },
  character: { fontSize: 62, lineHeight: 67, marginTop: -7 },
  armor: { fontSize: 43, lineHeight: 48, marginTop: -8 },
  boots: { fontSize: 25, lineHeight: 30, marginTop: -5 },
  tapGuide: { color: COLORS.textSecondary, fontSize: 12, fontWeight: '800' },
  shopButton: { minHeight: 50, width: '100%', alignItems: 'center', justifyContent: 'center', marginTop: 14, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
  shopButtonText: { color: COLORS.textOnPrimary, fontSize: 16, fontWeight: '900' },
  missionHeader: { marginTop: 28, marginBottom: 14 },
  sectionTitle: { color: COLORS.textPrimary, fontSize: 22, fontWeight: '900' },
  sectionCaption: { color: COLORS.textSecondary, fontSize: 13, fontWeight: '600', marginTop: 5 },
  missionGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 12 },
  missionCard: { ...SHADOWS.soft, width: '48%', minHeight: 174, padding: 17, borderRadius: BORDER_RADIUS.card },
  missionPressed: { opacity: 0.82, transform: [{ scale: 0.97 }] },
  missionEmojiCircle: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.cardBackground },
  missionEmoji: { fontSize: 25 },
  missionTitle: { color: COLORS.textPrimary, fontSize: 16, lineHeight: 22, fontWeight: '900', marginTop: 12 },
  missionDescription: { color: COLORS.textSecondary, fontSize: 11, lineHeight: 16, fontWeight: '700', marginTop: 3, paddingRight: 16 },
  missionArrow: { position: 'absolute', right: 16, bottom: 14, color: COLORS.textPrimary, fontSize: 19, fontWeight: '900' },
  noticeBanner: { ...SHADOWS.soft, flexDirection: 'row', alignItems: 'center', marginTop: 14, padding: 16, borderRadius: BORDER_RADIUS.card, backgroundColor: '#FFF8E4' },
  noticeBannerPressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
  noticeBannerEmoji: { fontSize: 26, marginRight: 13 },
  noticeBannerCopy: { flex: 1 },
  noticeBannerTitle: { color: COLORS.textPrimary, fontSize: 15, fontWeight: '900' },
  noticeBannerDescription: { marginTop: 3, color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  noticeBannerArrow: { color: COLORS.textSecondary, fontSize: 20, fontWeight: '900' },
});
