import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, SHADOWS } from '@/constants/theme';

export const manitoStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  keyboardView: { flex: 1 },
  scrollContent: { flexGrow: 1, alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48 },
  content: { width: '100%', maxWidth: 520 },
  header: { marginBottom: 18 },
  title: { color: COLORS.textPrimary, fontSize: 22, fontWeight: '900' },
  caption: { marginTop: 5, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  buddyCard: { ...SHADOWS.soft, alignItems: 'center', padding: 24, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.primarySoft, marginBottom: 18 },
  buddyLabel: { color: COLORS.primary, fontSize: 12, fontWeight: '900' },
  buddyAvatarCircle: { width: 72, height: 72, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.cardBackground, marginTop: 12 },
  buddyAvatar: { fontSize: 36 },
  buddyName: { marginTop: 10, color: COLORS.textPrimary, fontSize: 20, fontWeight: '900' },
  secretNote: { marginTop: 8, color: COLORS.textSecondary, fontSize: 12, lineHeight: 18, fontWeight: '600', textAlign: 'center' },
  card: { ...SHADOWS.soft, marginBottom: 18, padding: 20, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  sectionTitle: { color: COLORS.textPrimary, fontSize: 17, fontWeight: '900' },
  sectionGuide: { marginTop: 6, color: COLORS.textSecondary, fontSize: 13, lineHeight: 20, fontWeight: '600' },
  input: { minHeight: 70, marginTop: 14, padding: 16, borderWidth: 2, borderColor: COLORS.disabled, borderRadius: 18, backgroundColor: COLORS.surfaceMuted, color: COLORS.textPrimary, fontSize: 15, lineHeight: 22, fontWeight: '700', textAlignVertical: 'top' },
  inputFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  safeHint: { flex: 1, color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  counter: { color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  sendButton: { minHeight: 56, alignItems: 'center', justifyContent: 'center', marginTop: 14, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
  sendDisabled: { backgroundColor: COLORS.disabled },
  sendText: { color: COLORS.textOnPrimary, fontSize: 16, fontWeight: '900' },
  inboxHeader: { marginBottom: 14 },
  prayerCard: { ...SHADOWS.soft, marginBottom: 12, padding: 16, borderRadius: BORDER_RADIUS.card, backgroundColor: '#EEEAFB' },
  prayerRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  prayerSender: { color: COLORS.textSecondary, fontSize: 12, fontWeight: '800' },
  prayerTime: { color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  prayerMessage: { marginTop: 10, color: COLORS.textPrimary, fontSize: 15, lineHeight: 22, fontWeight: '700' },
  pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
  modalBackdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: 'rgba(41, 42, 45, 0.35)' },
  modalCard: { ...SHADOWS.soft, width: '100%', maxWidth: 380, alignItems: 'center', padding: 26, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  modalEmoji: { fontSize: 44 },
  modalTitle: { marginTop: 12, color: COLORS.textPrimary, fontSize: 20, fontWeight: '900', textAlign: 'center' },
  modalBody: { marginTop: 10, color: COLORS.textSecondary, fontSize: 14, lineHeight: 21, fontWeight: '600', textAlign: 'center' },
  modalButton: { minHeight: 52, alignItems: 'center', justifyContent: 'center', alignSelf: 'stretch', marginTop: 20, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
});
