import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, SHADOWS } from '@/constants/theme';

export const monthlyCalendarStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  scrollContent: { flexGrow: 1, alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48 },
  content: { width: '100%', maxWidth: 520 },
  header: { marginBottom: 18 },
  title: { color: COLORS.textPrimary, fontSize: 22, fontWeight: '900' },
  caption: { marginTop: 5, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  summaryCard: { ...SHADOWS.soft, padding: 20, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.primarySoft, marginBottom: 18 },
  summaryTitle: { color: COLORS.primary, fontSize: 12, fontWeight: '900' },
  summaryRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6, marginTop: 8 },
  summaryRate: { color: COLORS.textPrimary, fontSize: 32, fontWeight: '900' },
  summaryRateUnit: { color: COLORS.textPrimary, fontSize: 16, fontWeight: '900' },
  summaryDetail: { marginTop: 4, color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  progressTrack: { height: 12, overflow: 'hidden', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.cardBackground, marginTop: 14 },
  progressFill: { height: '100%', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primary },
  resetNote: { marginTop: 12, color: COLORS.textSecondary, fontSize: 11, lineHeight: 16, fontWeight: '600' },
  calendarCard: { ...SHADOWS.soft, padding: 18, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  monthLabel: { color: COLORS.textPrimary, fontSize: 17, fontWeight: '900', marginBottom: 14 },
  weekdayRow: { flexDirection: 'row' },
  weekdayCell: { width: `${100 / 7}%`, alignItems: 'center', paddingBottom: 8 },
  weekdayText: { color: COLORS.textSecondary, fontSize: 12, fontWeight: '800' },
  dayGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  dayCell: { width: `${100 / 7}%`, aspectRatio: 1, alignItems: 'center', justifyContent: 'center', padding: 2 },
  dayCellInner: { width: '86%', height: '86%', alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge },
  dayCellToday: { borderWidth: 2, borderColor: COLORS.primary },
  dayCellCompleted: { backgroundColor: COLORS.primarySoft },
  dayNumber: { color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  dayNumberFuture: { color: COLORS.disabled },
  stickerEmoji: { fontSize: 18 },
  legendRow: { flexDirection: 'row', gap: 16, marginTop: 16 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendEmoji: { fontSize: 14 },
  legendText: { color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
});
