import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, Fonts, SHADOWS } from '@/constants/theme';

export const monthlyCalendarStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  scrollContent: { flexGrow: 1, alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48 },
  content: { width: '100%', maxWidth: 520 },
  header: { marginBottom: 18 },
  title: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 22 },
  caption: { fontFamily: Fonts.sans, marginTop: 5, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  summaryCard: { ...SHADOWS.soft, padding: 20, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.primarySoft, marginBottom: 18 },
  summaryTitle: { fontFamily: Fonts.sans, color: COLORS.primary, fontSize: 12, fontWeight: '900' },
  summaryRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6, marginTop: 8 },
  summaryRate: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 32 },
  summaryRateUnit: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 16, fontWeight: '900' },
  summaryDetail: { fontFamily: Fonts.sans, marginTop: 4, color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  progressTrack: { height: 12, overflow: 'hidden', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.cardBackground, marginTop: 14 },
  progressFill: { height: '100%', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primary },
  resetNote: { fontFamily: Fonts.sans, marginTop: 12, color: COLORS.textSecondary, fontSize: 11, lineHeight: 16, fontWeight: '600' },
  calendarCard: { ...SHADOWS.soft, padding: 18, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  monthLabel: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 17, fontWeight: '900', marginBottom: 14 },
  weekdayRow: { flexDirection: 'row' },
  weekdayCell: { width: `${100 / 7}%`, alignItems: 'center', paddingBottom: 8 },
  weekdayText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 12, fontWeight: '800' },
  dayGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  dayCell: { width: `${100 / 7}%`, aspectRatio: 1, alignItems: 'center', justifyContent: 'center', padding: 2 },
  dayCellInner: { width: '86%', height: '86%', alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge },
  dayCellToday: { borderWidth: 2, borderColor: COLORS.primary },
  dayCellCompleted: { backgroundColor: COLORS.primarySoft },
  dayNumber: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  dayNumberFuture: { color: COLORS.disabled },
  stickerEmoji: { fontFamily: Fonts.sans, fontSize: 18 },
  legendRow: { flexDirection: 'row', gap: 16, marginTop: 16 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendEmoji: { fontFamily: Fonts.sans, fontSize: 14 },
  legendText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  // 매일 알림 카드
  reminderCard: { marginTop: 18, padding: 18 },
  reminderTopRow: { flexDirection: 'row', alignItems: 'center' },
  reminderCopy: { flex: 1, marginRight: 12 },
  reminderTitle: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 16 },
  reminderCaption: { fontFamily: Fonts.sans, marginTop: 4, color: COLORS.textSecondary, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  reminderSwitch: { width: 50, height: 30, borderRadius: 15, padding: 3, justifyContent: 'center', backgroundColor: COLORS.disabled },
  reminderSwitchOn: { backgroundColor: COLORS.primary },
  reminderSwitchDisabled: { opacity: 0.45 },
  reminderKnob: { width: 24, height: 24, borderRadius: 12, backgroundColor: COLORS.surfaceOpaque },
  reminderKnobOn: { alignSelf: 'flex-end' },
  reminderTimeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 },
  reminderTimeChip: { paddingHorizontal: 13, paddingVertical: 8, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.surfaceMuted },
  reminderTimeChipOn: { backgroundColor: COLORS.primarySoft },
  reminderTimeText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 13, fontWeight: '800' },
  reminderTimeTextOn: { color: COLORS.primary },
});
