import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, Fonts, SHADOWS } from '@/constants/theme';

export const qtStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  keyboardView: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 48,
  },
  content: { width: '100%', maxWidth: 520 },
  backButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: BORDER_RADIUS.badge,
    backgroundColor: COLORS.surfaceMuted,
  },
  backText: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 14, fontWeight: '800' },
  header: { marginTop: 22, marginBottom: 18 },
  title: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 27, lineHeight: 36 },
  date: { fontFamily: Fonts.sans, marginTop: 5, color: COLORS.textSecondary, fontSize: 14, fontWeight: '700' },
  card: {
    ...SHADOWS.soft,
    marginBottom: 16,
    padding: 20,
    borderRadius: BORDER_RADIUS.card,
    backgroundColor: COLORS.cardBackground,
  },
  verseCard: { backgroundColor: COLORS.accentSoft },
  sectionLabel: { fontFamily: Fonts.sans, color: COLORS.accent, fontSize: 12, fontWeight: '900' },
  reference: { fontFamily: Fonts.sans, marginTop: 7, color: COLORS.textPrimary, fontSize: 19, fontWeight: '900' },
  verse: { fontFamily: Fonts.sans, marginTop: 13, color: COLORS.textPrimary, fontSize: 18, lineHeight: 30, fontWeight: '700' },
  audioRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 20 },
  audioButton: {
    minWidth: 116,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    borderRadius: BORDER_RADIUS.button,
    backgroundColor: COLORS.accent,
  },
  audioButtonText: { fontFamily: Fonts.sans, color: COLORS.textOnPrimary, fontSize: 15, fontWeight: '900' },
  progressTrack: { flex: 1, height: 9, overflow: 'hidden', borderRadius: 9, backgroundColor: COLORS.disabled },
  progressFill: { height: '100%', borderRadius: 9, backgroundColor: COLORS.primary },
  audioHint: { fontFamily: Fonts.sans, marginTop: 10, color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  teacherCard: { backgroundColor: '#FFF8E4' },
  sectionTitle: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 19 },
  teacherMessage: { fontFamily: Fonts.sans, marginTop: 12, color: COLORS.textPrimary, fontSize: 16, lineHeight: 26, fontWeight: '600' },
  input: { fontFamily: Fonts.sans,
    minHeight: 116,
    marginTop: 14,
    padding: 16,
    borderWidth: 2,
    borderColor: COLORS.disabled,
    borderRadius: 18,
    backgroundColor: COLORS.surfaceMuted,
    color: COLORS.textPrimary,
    fontSize: 16,
    lineHeight: 24,
    textAlignVertical: 'top',
  },
  inputFocused: { borderColor: COLORS.accent },
  inputFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  safeHint: { fontFamily: Fonts.sans, flex: 1, color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  counter: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  submitButton: {
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    paddingHorizontal: 16,
    borderRadius: BORDER_RADIUS.button,
    backgroundColor: COLORS.primary,
  },
  submitDisabled: { backgroundColor: COLORS.disabled },
  submitText: { fontFamily: Fonts.sans, color: COLORS.textOnPrimary, fontSize: 16, fontWeight: '900', textAlign: 'center' },
  submitTextDisabled: { color: COLORS.textSecondary },
  completedBox: { marginTop: 14, padding: 16, borderRadius: 18, backgroundColor: COLORS.primarySoft },
  rewardText: { fontFamily: Fonts.sans, color: COLORS.primary, fontSize: 18, fontWeight: '900' },
  myReflection: { fontFamily: Fonts.sans, marginTop: 10, color: COLORS.textPrimary, fontSize: 16, lineHeight: 25, fontWeight: '700' },
  lockedCard: { alignItems: 'center', backgroundColor: COLORS.surfaceMuted },
  lockIcon: { fontFamily: Fonts.sans, fontSize: 32 },
  lockedText: { fontFamily: Fonts.sans, marginTop: 10, color: COLORS.textSecondary, fontSize: 16, lineHeight: 24, fontWeight: '800', textAlign: 'center' },
  feedTitle: { fontFamily: Fonts.sans, marginVertical: 8, color: COLORS.textPrimary, fontSize: 22, fontWeight: '900' },
  friendCard: { backgroundColor: COLORS.accentSoft },
  friendName: { fontFamily: Fonts.sans, color: COLORS.accent, fontSize: 16, fontWeight: '900' },
  friendReflection: { fontFamily: Fonts.sans, marginTop: 8, color: COLORS.textPrimary, fontSize: 16, lineHeight: 25, fontWeight: '700' },
  reactionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 16 },
  reactionButton: { minHeight: 40, justifyContent: 'center', paddingHorizontal: 11, borderWidth: 1, borderColor: COLORS.disabled, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.cardBackground },
  reactionSelected: { borderColor: COLORS.primary, backgroundColor: COLORS.primarySoft },
  reactionText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 12, fontWeight: '800' },
  reactionTextSelected: { color: COLORS.primary },
  reactionFeedback: { fontFamily: Fonts.sans, marginTop: 10, color: COLORS.success, fontSize: 12, fontWeight: '800' },
  modalBackdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: 'rgba(41, 42, 45, 0.35)' },
  modalCard: { ...SHADOWS.soft, width: '100%', maxWidth: 380, alignItems: 'center', padding: 24, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.surfaceOpaque },
  modalEmoji: { fontFamily: Fonts.sans, fontSize: 40 },
  modalTitle: { fontFamily: Fonts.display, marginTop: 10, color: COLORS.textPrimary, fontSize: 21, textAlign: 'center' },
  modalMessage: { fontFamily: Fonts.sans, marginTop: 10, color: COLORS.textSecondary, fontSize: 15, lineHeight: 23, fontWeight: '700', textAlign: 'center' },
  modalButton: { width: '100%', minHeight: 52, alignItems: 'center', justifyContent: 'center', marginTop: 20, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
  modalButtonText: { fontFamily: Fonts.sans, color: COLORS.textOnPrimary, fontSize: 16, fontWeight: '900' },
  pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
});
