import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, SHADOWS } from '@/constants/theme';

export const qtStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  keyboardView: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 48,
  },
  content: { width: '100%', maxWidth: 520 },
  backButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: BORDER_RADIUS.badge,
    backgroundColor: COLORS.surfaceMuted,
  },
  backText: { color: COLORS.textPrimary, fontSize: 14, fontWeight: '800' },
  header: { marginTop: 22, marginBottom: 18 },
  title: { color: COLORS.textPrimary, fontSize: 27, lineHeight: 36, fontWeight: '900' },
  date: { marginTop: 5, color: COLORS.textSecondary, fontSize: 14, fontWeight: '700' },
  card: {
    ...SHADOWS.soft,
    marginBottom: 16,
    padding: 20,
    borderRadius: BORDER_RADIUS.card,
    backgroundColor: COLORS.cardBackground,
  },
  verseCard: { backgroundColor: COLORS.accentSoft },
  sectionLabel: { color: COLORS.accent, fontSize: 12, fontWeight: '900' },
  reference: { marginTop: 7, color: COLORS.textPrimary, fontSize: 19, fontWeight: '900' },
  verse: { marginTop: 13, color: COLORS.textPrimary, fontSize: 18, lineHeight: 30, fontWeight: '700' },
  audioRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 20 },
  audioButton: {
    minWidth: 116,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    borderRadius: BORDER_RADIUS.button,
    backgroundColor: COLORS.accent,
  },
  audioButtonText: { color: COLORS.textOnPrimary, fontSize: 15, fontWeight: '900' },
  progressTrack: { flex: 1, height: 9, overflow: 'hidden', borderRadius: 9, backgroundColor: COLORS.disabled },
  progressFill: { height: '100%', borderRadius: 9, backgroundColor: COLORS.primary },
  audioHint: { marginTop: 10, color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  teacherCard: { backgroundColor: '#FFF8E4' },
  sectionTitle: { color: COLORS.textPrimary, fontSize: 19, fontWeight: '900' },
  teacherMessage: { marginTop: 12, color: COLORS.textPrimary, fontSize: 16, lineHeight: 26, fontWeight: '600' },
  input: {
    minHeight: 116,
    marginTop: 14,
    padding: 16,
    borderWidth: 2,
    borderColor: COLORS.disabled,
    borderRadius: 18,
    backgroundColor: COLORS.surfaceMuted,
    color: COLORS.textPrimary,
    fontSize: 16,
    lineHeight: 24,
    textAlignVertical: 'top',
  },
  inputFocused: { borderColor: COLORS.accent },
  inputFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  safeHint: { flex: 1, color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  counter: { color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  submitButton: {
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    paddingHorizontal: 16,
    borderRadius: BORDER_RADIUS.button,
    backgroundColor: COLORS.primary,
  },
  submitDisabled: { backgroundColor: COLORS.disabled },
  submitText: { color: COLORS.textOnPrimary, fontSize: 16, fontWeight: '900', textAlign: 'center' },
  submitTextDisabled: { color: COLORS.textSecondary },
  pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
});
