import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, Fonts, MaxContentWidth, SHADOWS } from '@/constants/theme';

export const teacherSafetyStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  scrollContent: { alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48 },
  content: { width: '100%', maxWidth: MaxContentWidth },
  header: { marginBottom: 16 },
  title: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 22 },
  caption: { fontFamily: Fonts.sans, marginTop: 5, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  infoCard: { ...SHADOWS.soft, padding: 16, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.accentSoft, marginBottom: 18 },
  infoText: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  tabRow: { flexDirection: 'row', gap: 8, marginBottom: 18, padding: 5, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.surfaceMuted },
  tabButton: { flex: 1, alignItems: 'center', paddingVertical: 11, borderRadius: BORDER_RADIUS.badge },
  tabButtonActive: { ...SHADOWS.soft, backgroundColor: COLORS.cardBackground },
  tabText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 14, fontWeight: '800' },
  tabTextActive: { color: COLORS.primary },
  postCard: { ...SHADOWS.soft, marginBottom: 12, padding: 16, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  postCardBlocked: { opacity: 0.6 },
  postHeader: { flexDirection: 'row', alignItems: 'center' },
  avatarCircle: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primarySoft },
  avatar: { fontFamily: Fonts.sans, fontSize: 20 },
  postIdentity: { flex: 1, marginLeft: 11 },
  studentName: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 15 },
  sourceBadge: { fontFamily: Fonts.sans, marginTop: 3, color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  flaggedAt: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  contentBox: { marginTop: 12, padding: 12, borderRadius: 14, backgroundColor: COLORS.surfaceMuted },
  contentText: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 14, lineHeight: 21, fontWeight: '600' },
  flaggedWordChip: { alignSelf: 'flex-start', marginTop: 10, paddingHorizontal: 10, paddingVertical: 4, borderRadius: BORDER_RADIUS.badge, backgroundColor: '#FCE9EA' },
  flaggedWordText: { fontFamily: Fonts.sans, color: '#C1544C', fontSize: 11, fontWeight: '900' },
  actionRow: { flexDirection: 'row', gap: 10, marginTop: 14 },
  actionButton: { flex: 1, minHeight: 46, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.button },
  approveButton: { backgroundColor: COLORS.success },
  blockButton: { backgroundColor: '#C1544C' },
  actionButtonText: { fontFamily: Fonts.sans, color: COLORS.textOnPrimary, fontSize: 13, fontWeight: '900' },
  statusBadge: { alignSelf: 'flex-start', marginTop: 12, paddingHorizontal: 12, paddingVertical: 6, borderRadius: BORDER_RADIUS.badge },
  statusBadgeApproved: { backgroundColor: '#E3F3E1' },
  statusBadgeBlocked: { backgroundColor: '#FCE9EA' },
  statusBadgeText: { fontFamily: Fonts.sans, fontSize: 12, fontWeight: '900' },
  statusBadgeTextApproved: { color: COLORS.success },
  statusBadgeTextBlocked: { color: '#C1544C' },
  emptyState: { alignItems: 'center', paddingVertical: 40 },
  emptyText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 14, fontWeight: '700' },
  pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
});
