import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, Fonts, MaxContentWidth, SHADOWS } from '@/constants/theme';

export const teacherContentManageStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  keyboardView: { flex: 1 },
  scrollContent: { alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48 },
  content: { width: '100%', maxWidth: MaxContentWidth },
  header: { marginBottom: 16 },
  title: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 22 },
  caption: { fontFamily: Fonts.sans, marginTop: 5, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  tabRow: { flexDirection: 'row', gap: 8, marginBottom: 18, padding: 5, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.surfaceMuted },
  tabButton: { flex: 1, alignItems: 'center', paddingVertical: 11, borderRadius: BORDER_RADIUS.badge },
  tabButtonActive: { ...SHADOWS.soft, backgroundColor: COLORS.cardBackground },
  tabText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 14, fontWeight: '800' },
  tabTextActive: { color: COLORS.primary },
  addButton: { ...SHADOWS.soft, minHeight: 54, alignItems: 'center', justifyContent: 'center', marginBottom: 18, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
  addButtonText: { fontFamily: Fonts.sans, color: COLORS.textOnPrimary, fontSize: 15, fontWeight: '900' },
  list: { gap: 12 },
  itemCard: { ...SHADOWS.soft, padding: 16, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  itemCardPinned: { borderWidth: 2, borderColor: COLORS.primary, backgroundColor: COLORS.primarySoft },
  pinnedBadge: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 4, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primary, marginBottom: 8 },
  pinnedBadgeText: { fontFamily: Fonts.sans, color: COLORS.textOnPrimary, fontSize: 11, fontWeight: '900' },
  itemHeaderRow: { flexDirection: 'row', alignItems: 'center' },
  itemEmojiCircle: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.accentSoft },
  itemEmoji: { fontFamily: Fonts.sans, fontSize: 20 },
  itemBody: { flex: 1, marginLeft: 12 },
  itemTitle: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 16 },
  itemDate: { fontFamily: Fonts.sans, marginTop: 3, color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  itemContent: { fontFamily: Fonts.sans, marginTop: 12, color: COLORS.textPrimary, fontSize: 14, lineHeight: 21, fontWeight: '600' },
  itemActionRow: { flexDirection: 'row', gap: 8, marginTop: 14 },
  actionButton: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.surfaceMuted },
  actionButtonText: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 13, fontWeight: '800' },
  deleteButton: { backgroundColor: '#FCE9EA' },
  deleteButtonText: { color: '#C1544C' },
  pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
  modalBackdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: 'rgba(41, 42, 45, 0.38)' },
  modalCard: { width: '100%', maxWidth: 440, maxHeight: '86%', padding: 24, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.surfaceOpaque },
  modalTitle: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 19 },
  modalLabel: { fontFamily: Fonts.sans, marginTop: 16, marginBottom: 8, color: COLORS.textPrimary, fontSize: 13, fontWeight: '800' },
  input: { fontFamily: Fonts.sans, minHeight: 50, paddingHorizontal: 14, borderWidth: 2, borderColor: COLORS.disabled, borderRadius: 16, backgroundColor: COLORS.surfaceMuted, color: COLORS.textPrimary, fontSize: 15, fontWeight: '700' },
  textArea: { minHeight: 90, paddingTop: 14, textAlignVertical: 'top' },
  emojiRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  emojiOption: { width: 46, height: 46, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.surfaceMuted },
  emojiOptionSelected: { backgroundColor: COLORS.primarySoft, borderWidth: 2, borderColor: COLORS.primary },
  emojiOptionText: { fontFamily: Fonts.sans, fontSize: 21 },
  pinToggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 18, padding: 14, borderRadius: 16, backgroundColor: COLORS.surfaceMuted },
  pinToggleLabel: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 14, fontWeight: '800' },
  pinToggleSwitch: { width: 46, height: 28, borderRadius: 14, padding: 3, backgroundColor: COLORS.disabled },
  pinToggleSwitchOn: { backgroundColor: COLORS.primary },
  pinToggleKnob: { width: 22, height: 22, borderRadius: 11, backgroundColor: COLORS.cardBackground },
  pinToggleKnobOn: { alignSelf: 'flex-end' },
  modalButtonRow: { flexDirection: 'row', gap: 10, marginTop: 22 },
  cancelButton: { flex: 1, minHeight: 52, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.surfaceMuted },
  cancelButtonText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 15, fontWeight: '900' },
  submitButton: { flex: 1.4, minHeight: 52, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
  submitButtonDisabled: { backgroundColor: COLORS.disabled },
  submitButtonText: { fontFamily: Fonts.sans, color: COLORS.textOnPrimary, fontSize: 15, fontWeight: '900' },
  // 영상 등록 관리 전용 스타일
  categoryRow: { flexDirection: 'row', gap: 8, marginBottom: 18 },
  categoryChip: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.surfaceMuted },
  categoryChipActive: { backgroundColor: COLORS.primarySoft },
  categoryChipText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 13, fontWeight: '800' },
  categoryChipTextActive: { color: COLORS.primary },
  videoCard: { ...SHADOWS.soft, flexDirection: 'row', alignItems: 'center', marginBottom: 12, padding: 14, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  videoThumb: { width: 56, height: 56, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.card },
  videoThumbEmoji: { fontFamily: Fonts.sans, fontSize: 26 },
  videoBody: { flex: 1, marginLeft: 13 },
  videoCategoryBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 3, borderRadius: BORDER_RADIUS.badge, backgroundColor: '#FFF8E4', marginBottom: 6 },
  videoCategoryText: { fontFamily: Fonts.sans, color: COLORS.warning, fontSize: 10, fontWeight: '900' },
  videoTitle: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 14 },
  videoDuration: { fontFamily: Fonts.sans, marginTop: 4, color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  videoDeleteButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: '#FCE9EA', marginLeft: 8 },
  videoDeleteIcon: { fontFamily: Fonts.sans, fontSize: 16 },
});
