import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, MaxContentWidth, SHADOWS } from '@/constants/theme';

export const teacherStudentManageStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  scrollContent: { alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48 },
  content: { width: '100%', maxWidth: MaxContentWidth },
  header: { marginBottom: 16 },
  title: { color: COLORS.textPrimary, fontSize: 22, fontWeight: '900' },
  caption: { marginTop: 5, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  addButton: { ...SHADOWS.soft, minHeight: 56, alignItems: 'center', justifyContent: 'center', marginBottom: 20, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
  addButtonText: { color: COLORS.textOnPrimary, fontSize: 16, fontWeight: '900' },
  sectionTitle: { marginBottom: 14, color: COLORS.textPrimary, fontSize: 17, fontWeight: '900' },
  studentList: { gap: 12 },
  studentCard: { ...SHADOWS.soft, flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  avatarCircle: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primarySoft },
  avatar: { fontSize: 24 },
  studentBody: { flex: 1, marginLeft: 13 },
  studentName: { color: COLORS.textPrimary, fontSize: 16, fontWeight: '900' },
  registeredAt: { marginTop: 4, color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  resetButton: { minHeight: 40, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.surfaceMuted },
  resetButtonText: { color: COLORS.textPrimary, fontSize: 12, fontWeight: '800' },
  pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
  modalBackdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: 'rgba(41, 42, 45, 0.38)' },
  modalCard: { width: '100%', maxWidth: 420, padding: 26, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  modalTitle: { color: COLORS.textPrimary, fontSize: 20, fontWeight: '900' },
  modalCaption: { marginTop: 6, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  modalLabel: { marginTop: 18, marginBottom: 10, color: COLORS.textPrimary, fontSize: 13, fontWeight: '800' },
  input: { minHeight: 52, paddingHorizontal: 16, borderWidth: 2, borderColor: COLORS.disabled, borderRadius: 16, backgroundColor: COLORS.surfaceMuted, color: COLORS.textPrimary, fontSize: 15, fontWeight: '700' },
  avatarPickerRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  avatarOption: { width: 52, height: 52, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.surfaceMuted },
  avatarOptionSelected: { backgroundColor: COLORS.primarySoft, borderWidth: 2, borderColor: COLORS.primary },
  avatarOptionEmoji: { fontSize: 24 },
  pinNoteBox: { marginTop: 18, padding: 12, borderRadius: 14, backgroundColor: COLORS.primarySoft },
  pinNoteText: { color: COLORS.primary, fontSize: 12, fontWeight: '800' },
  modalButtonRow: { flexDirection: 'row', gap: 10, marginTop: 22 },
  cancelButton: { flex: 1, minHeight: 52, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.surfaceMuted },
  cancelButtonText: { color: COLORS.textSecondary, fontSize: 15, fontWeight: '900' },
  submitButton: { flex: 1.4, minHeight: 52, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
  submitButtonDisabled: { backgroundColor: COLORS.disabled },
  submitButtonText: { color: COLORS.textOnPrimary, fontSize: 15, fontWeight: '900' },
});
