import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, Fonts, MaxContentWidth, SHADOWS } from '@/constants/theme';

export const teacherHomeStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  scrollContent: { alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48 },
  content: { width: '100%', maxWidth: MaxContentWidth },
  summaryCard: { ...SHADOWS.soft, padding: 22, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.primarySoft },
  eyebrow: { fontFamily: Fonts.sans, color: COLORS.primary, fontSize: 12, fontWeight: '900' },
  title: { fontFamily: Fonts.display, marginTop: 6, color: COLORS.textPrimary, fontSize: 24, lineHeight: 32 },
  participationRow: { flexDirection: 'row', alignItems: 'center', gap: 14, marginTop: 20 },
  participationText: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 16, fontWeight: '800' },
  progressTrack: { flex: 1, height: 12, overflow: 'hidden', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.cardBackground },
  progressFill: { height: '100%', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primary },
  sectionHeader: { marginTop: 30, marginBottom: 14 },
  sectionTitle: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 21 },
  sectionCaption: { fontFamily: Fonts.sans, marginTop: 5, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  shortcutList: { gap: 10 },
  shortcut: { ...SHADOWS.soft, minHeight: 78, flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: BORDER_RADIUS.card },
  shortcutPressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
  shortcutEmoji: { fontFamily: Fonts.sans, fontSize: 28, marginRight: 13 },
  shortcutCopy: { flex: 1 },
  shortcutTitle: { fontFamily: Fonts.sans, color: COLORS.textPrimary, fontSize: 16, fontWeight: '900' },
  shortcutDescription: { fontFamily: Fonts.sans, marginTop: 4, color: COLORS.textSecondary, fontSize: 12, fontWeight: '700' },
  arrow: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 22, fontWeight: '900' },
  studentList: { gap: 12 },
  studentCard: { ...SHADOWS.soft, padding: 16, borderWidth: 2, borderColor: 'transparent', borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  studentCardSelected: { borderColor: COLORS.primary, backgroundColor: COLORS.primarySoft },
  studentCardPressed: { opacity: 0.8, transform: [{ scale: 0.99 }] },
  studentMainRow: { flexDirection: 'row', alignItems: 'center' },
  avatarCircle: { width: 52, height: 52, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.accentSoft },
  avatar: { fontFamily: Fonts.sans, fontSize: 29 },
  studentInfo: { flex: 1, marginLeft: 13 },
  nameRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 7 },
  studentName: { fontFamily: Fonts.display, color: COLORS.textPrimary, fontSize: 17 },
  streakBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: BORDER_RADIUS.badge, backgroundColor: '#FFF8E4' },
  streakText: { fontFamily: Fonts.sans, color: COLORS.warning, fontSize: 11, fontWeight: '900' },
  activityRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 7 },
  activityText: { fontFamily: Fonts.sans, color: COLORS.textSecondary, fontSize: 12, fontWeight: '800' },
  talent: { fontFamily: Fonts.sans, marginLeft: 8, color: COLORS.textPrimary, fontSize: 13, fontWeight: '900' },
  nudgeButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center', marginTop: 14, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
  nudgeButtonPressed: { opacity: 0.76, transform: [{ scale: 0.98 }] },
  nudgeButtonText: { fontFamily: Fonts.sans, color: COLORS.textOnPrimary, fontSize: 14, fontWeight: '900' },
});
