import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, MaxContentWidth, SHADOWS } from '@/constants/theme';

export const teacherTemplateStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  keyboardView: { flex: 1 },
  scrollContent: { alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48 },
  content: { width: '100%', maxWidth: MaxContentWidth },
  header: { marginBottom: 16 },
  title: { color: COLORS.textPrimary, fontSize: 22, fontWeight: '900' },
  caption: { marginTop: 5, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  dayRow: { flexDirection: 'row', gap: 8, marginBottom: 18 },
  dayTab: { flex: 1, alignItems: 'center', paddingVertical: 12, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.surfaceMuted },
  dayTabActive: { ...SHADOWS.soft, backgroundColor: COLORS.primarySoft },
  dayLabel: { color: COLORS.textSecondary, fontSize: 15, fontWeight: '900' },
  dayLabelActive: { color: COLORS.primary },
  dayStatusDot: { width: 6, height: 6, borderRadius: 3, marginTop: 5, backgroundColor: COLORS.disabled },
  dayStatusDotPublished: { backgroundColor: COLORS.success },
  card: { ...SHADOWS.soft, marginBottom: 16, padding: 20, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  sectionTitle: { color: COLORS.textPrimary, fontSize: 17, fontWeight: '900' },
  sectionGuide: { marginTop: 6, color: COLORS.textSecondary, fontSize: 13, lineHeight: 20, fontWeight: '600' },
  label: { marginTop: 16, marginBottom: 8, color: COLORS.textPrimary, fontSize: 13, fontWeight: '800' },
  input: { minHeight: 50, paddingHorizontal: 14, borderWidth: 2, borderColor: COLORS.disabled, borderRadius: 16, backgroundColor: COLORS.surfaceMuted, color: COLORS.textPrimary, fontSize: 15, fontWeight: '700' },
  textArea: { minHeight: 90, paddingTop: 14, textAlignVertical: 'top' },
  voiceRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 18 },
  voiceButton: { flex: 1, minHeight: 52, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.accent },
  voiceButtonDone: { backgroundColor: COLORS.success },
  voiceButtonText: { color: COLORS.textOnPrimary, fontSize: 14, fontWeight: '900' },
  publishButton: { minHeight: 56, alignItems: 'center', justifyContent: 'center', marginTop: 16, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
  publishButtonDone: { backgroundColor: COLORS.success },
  publishDisabled: { backgroundColor: COLORS.disabled },
  publishText: { color: COLORS.textOnPrimary, fontSize: 16, fontWeight: '900' },
  pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
});
