import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, MaxContentWidth, SHADOWS } from '@/constants/theme';

export const teacherMindTalkStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  scrollContent: { alignItems: 'center', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 48 },
  content: { width: '100%', maxWidth: MaxContentWidth },
  header: { marginBottom: 16 },
  title: { color: COLORS.textPrimary, fontSize: 22, fontWeight: '900' },
  caption: { marginTop: 5, color: COLORS.textSecondary, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  threadList: { gap: 12 },
  threadCard: { ...SHADOWS.soft, flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  avatarCircle: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primarySoft },
  avatar: { fontSize: 24 },
  threadBody: { flex: 1, marginLeft: 13 },
  nameRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  studentName: { color: COLORS.textPrimary, fontSize: 16, fontWeight: '900' },
  unreadDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.primary },
  lastMessage: { marginTop: 4, color: COLORS.textSecondary, fontSize: 13, fontWeight: '600' },
  threadTime: { color: COLORS.textSecondary, fontSize: 11, fontWeight: '700' },
  pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
  // 대화 화면 전용 스타일
  keyboardView: { flex: 1 },
  threadContent: { width: '100%', maxWidth: 620, flex: 1, alignSelf: 'center' },
  threadHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 16 },
  threadHeaderAvatar: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primarySoft, marginRight: 11 },
  threadHeaderName: { color: COLORS.textPrimary, fontSize: 19, fontWeight: '900' },
  listContent: { flexGrow: 1, paddingHorizontal: 20, paddingVertical: 8, gap: 16 },
  messageRow: { width: '100%', alignItems: 'flex-start' },
  teacherRow: { alignItems: 'flex-end' },
  senderLabel: { marginBottom: 6, color: COLORS.textSecondary, fontSize: 12, fontWeight: '800' },
  bubble: { ...SHADOWS.soft, maxWidth: '84%', padding: 16, borderRadius: BORDER_RADIUS.card, borderTopLeftRadius: 7, backgroundColor: COLORS.primarySoft },
  teacherBubble: { borderTopLeftRadius: BORDER_RADIUS.card, borderTopRightRadius: 7, backgroundColor: '#FFF8E4' },
  messageText: { color: COLORS.textPrimary, fontSize: 16, lineHeight: 24, fontWeight: '700' },
  timeText: { marginTop: 8, color: COLORS.textSecondary, fontSize: 11, fontWeight: '700', textAlign: 'right' },
  composer: { flexDirection: 'row', alignItems: 'flex-end', gap: 10, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 10, borderTopWidth: 1, borderTopColor: COLORS.disabled, backgroundColor: COLORS.cardBackground },
  voiceButton: { width: 54, height: 54, alignItems: 'center', justifyContent: 'center', borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.accentSoft },
  voiceIcon: { fontSize: 20 },
  input: { flex: 1, minHeight: 54, maxHeight: 110, paddingHorizontal: 16, paddingVertical: 14, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.surfaceMuted, color: COLORS.textPrimary, fontSize: 15, lineHeight: 21, fontWeight: '700' },
  sendButton: { minHeight: 54, justifyContent: 'center', paddingHorizontal: 16, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
  sendDisabled: { backgroundColor: COLORS.disabled },
  sendText: { color: COLORS.textOnPrimary, fontSize: 14, fontWeight: '900' },
  modalBackdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: 'rgba(41,42,45,0.38)' },
  modalCard: { width: '100%', maxWidth: 390, alignItems: 'center', padding: 26, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.cardBackground },
  modalEmoji: { fontSize: 48 },
  modalTitle: { marginTop: 10, color: COLORS.textPrimary, fontSize: 21, fontWeight: '900', textAlign: 'center' },
  modalBody: { marginTop: 10, color: COLORS.textSecondary, fontSize: 15, lineHeight: 23, fontWeight: '600', textAlign: 'center' },
  modalButton: { alignSelf: 'stretch', minHeight: 52, alignItems: 'center', justifyContent: 'center', marginTop: 20, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.primary },
});
