import { StyleSheet } from 'react-native';

const SOFT_SHADOW = {
  shadowColor: '#776F65',
  shadowOffset: { width: 0, height: 8 },
  shadowOpacity: 0.08,
  shadowRadius: 18,
  elevation: 3,
};

export const loginStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFFDF5' },
  keyboardView: { flex: 1 },
  scrollContent: { flexGrow: 1, alignItems: 'center', padding: 24, paddingBottom: 48, overflow: 'hidden' },
  peachBubble: { position: 'absolute', width: 210, height: 210, borderRadius: 105, top: -95, right: -70, backgroundColor: '#FFE7DC' },
  blueBubble: { position: 'absolute', width: 150, height: 150, borderRadius: 75, top: 150, left: -95, backgroundColor: '#E5F2F7' },
  header: { alignItems: 'center', marginTop: 12, marginBottom: 24 },
  brandBadge: { paddingHorizontal: 14, paddingVertical: 7, borderRadius: 24, backgroundColor: '#E9F4F7', marginBottom: 14 },
  brandBadgeText: { color: '#7895A0', fontSize: 11, fontWeight: '900', letterSpacing: 1.4 },
  logoSticker: { width: 88, height: 88, alignItems: 'center', justifyContent: 'center', borderRadius: 44, backgroundColor: '#FFF6E9', ...SOFT_SHADOW },
  logo: { fontSize: 50 },
  title: { color: '#383633', fontSize: 31, fontWeight: '900', letterSpacing: -1, textAlign: 'center', marginTop: 16 },
  subtitle: { color: '#89837B', fontSize: 15, fontWeight: '600', marginTop: 8, textAlign: 'center' },
  card: { width: '100%', maxWidth: 440, padding: 24, borderRadius: 32, backgroundColor: '#FFFFFF', ...SOFT_SHADOW },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', alignSelf: 'stretch', gap: 12, marginBottom: 16 },
  stepBadge: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 24, backgroundColor: '#FFE5D8' },
  stepBadgeBlue: { backgroundColor: '#DDEFF5' },
  stepText: { color: '#6B655E', fontSize: 17, fontWeight: '900' },
  sectionTitle: { color: '#403D39', fontSize: 18, fontWeight: '900', letterSpacing: -0.3 },
  sectionCaption: { color: '#A09A92', fontSize: 13, fontWeight: '600', marginTop: 2 },
  studentRow: { gap: 12, paddingBottom: 16, paddingHorizontal: 2 },
  studentButton: { minWidth: 100, minHeight: 118, alignItems: 'center', justifyContent: 'center', padding: 12, borderRadius: 28, backgroundColor: '#FAF8F3' },
  studentButtonSelected: { backgroundColor: '#FFF0E8', ...SOFT_SHADOW },
  studentPressed: { transform: [{ scale: 0.96 }] },
  characterBubble: { width: 58, height: 58, alignItems: 'center', justifyContent: 'center', borderRadius: 29, backgroundColor: '#FFFFFF' },
  studentEmoji: { fontSize: 34 },
  studentName: { color: '#5D5852', fontSize: 15, fontWeight: '800', marginTop: 8 },
  selectedCheck: { position: 'absolute', top: 9, right: 10, color: '#DC8F75', fontSize: 15, fontWeight: '900' },
  input: { width: '100%', height: 58, paddingHorizontal: 18, borderRadius: 24, backgroundColor: '#F3F7F8', color: '#484541', fontSize: 16, fontWeight: '700', marginBottom: 26 },
  pinHeader: { marginBottom: 14 },
  pinFeedback: { flexDirection: 'row', justifyContent: 'center', gap: 12, marginBottom: 18 },
  pinSlot: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 24, backgroundColor: '#F1F5F6' },
  pinSlotFilled: { backgroundColor: '#FFF1E8' },
  pinSymbol: { color: '#C5D2D6', fontSize: 25, fontWeight: '900', lineHeight: 30 },
  pinSymbolFilled: { fontSize: 22 },
  helperPill: { alignSelf: 'center', paddingHorizontal: 14, paddingVertical: 7, borderRadius: 24, backgroundColor: '#FFF7ED', marginTop: 16 },
  helper: { color: '#A78573', fontSize: 12, fontWeight: '800' },
  loginButton: { width: '100%', minHeight: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderRadius: 28, backgroundColor: '#E8E5DF', marginTop: 22, ...SOFT_SHADOW },
  loginButtonReady: { backgroundColor: '#F3B39E' },
  loginButtonPressed: { transform: [{ scale: 0.98 }] },
  loginButtonDisabled: { opacity: 0.62, shadowOpacity: 0 },
  loginText: { color: '#FFFFFF', fontSize: 18, fontWeight: '900' },
  loginArrow: { position: 'absolute', right: 24, color: '#FFFFFF', fontSize: 25, fontWeight: '700' },
});
