import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS } from '@/constants/theme';

export const loginStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  keyboardView: { flex: 1 },
  scrollContent: { flexGrow: 1, alignItems: 'center', padding: 24, paddingBottom: 48 },
  header: { width: '100%', maxWidth: 440, alignItems: 'flex-start', marginTop: 10, marginBottom: 22 },
  brandBadge: { paddingHorizontal: 13, paddingVertical: 7, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primarySoft, marginBottom: 16 },
  brandBadgeText: { color: COLORS.primary, fontSize: 12, fontWeight: '900' },
  title: { color: COLORS.textPrimary, fontSize: 30, lineHeight: 38, fontWeight: '900', letterSpacing: -1.2 },
  subtitle: { color: COLORS.textSecondary, fontSize: 15, lineHeight: 22, fontWeight: '600', marginTop: 6 },
  heroImage: { width: '100%', maxWidth: 440, aspectRatio: 1.55, borderRadius: 32, marginBottom: 20, backgroundColor: COLORS.secondary },
  card: { width: '100%', maxWidth: 440, padding: 24, borderRadius: 32 },
  sectionHeader: { alignSelf: 'stretch', marginBottom: 16 },
  sectionTitle: { color: COLORS.textPrimary, fontSize: 19, fontWeight: '900', letterSpacing: -0.4 },
  sectionCaption: { color: COLORS.textSecondary, fontSize: 13, fontWeight: '600', marginTop: 4 },
  studentRow: { gap: 10, paddingBottom: 16, paddingHorizontal: 2 },
  studentButton: { minWidth: 86, minHeight: 92, alignItems: 'center', justifyContent: 'center', padding: 12, borderRadius: BORDER_RADIUS.card, backgroundColor: COLORS.surfaceMuted },
  studentButtonSelected: { backgroundColor: COLORS.primarySoft },
  studentPressed: { transform: [{ scale: 0.96 }] },
  studentInitial: { color: COLORS.primary, fontSize: 27, lineHeight: 32, fontWeight: '900' },
  studentName: { color: COLORS.textPrimary, fontSize: 14, fontWeight: '800', marginTop: 5 },
  input: { width: '100%', height: 58, paddingHorizontal: 18, borderRadius: BORDER_RADIUS.button, backgroundColor: COLORS.surfaceMuted, color: COLORS.textPrimary, fontSize: 16, fontWeight: '700', marginBottom: 28 },
  pinHeader: { marginBottom: 14 },
  pinFeedback: { flexDirection: 'row', justifyContent: 'center', gap: 12, marginBottom: 18 },
  pinSlot: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 24, backgroundColor: COLORS.surfaceMuted },
  pinSlotFilled: { backgroundColor: COLORS.primarySoft },
  pinSymbol: { color: COLORS.textSecondary, fontSize: 25, fontWeight: '900', lineHeight: 30 },
  pinSymbolFilled: { fontSize: 22 },
  helperPill: { alignSelf: 'center', paddingHorizontal: 14, paddingVertical: 7, borderRadius: BORDER_RADIUS.badge, backgroundColor: COLORS.primarySoft, marginTop: 16 },
  helper: { color: COLORS.textSecondary, fontSize: 12, fontWeight: '800' },
  loginButton: { width: '100%', marginTop: 22 },
});
